### ISSUE TITLE
Problem with gene-level statistic

### ISSUE THREAD

**Issue by gyzsolt91** [LiuzLab/CB2#10]
Hi,

I managed to run sgRNA-level statistic, but when I try to make gene-level statistic with measure_gene_stats() function I get these error messages:
`Error in library.dynam(lib, package, package.lib) : 
  shared object ‘Matrix.so’ not found
In addition: Warning message:
S3 methods ‘print.sparseSummary’, ‘print.diagSummary’, ‘c.abIndex’, ‘c.sparseVector’, ‘as.array.Matrix’, ‘as.array.sparseVector’, ‘as.matrix.Matrix’, ‘as.matrix.sparseVector’, ‘as.vector.Matrix’, ‘as.vector.sparseVector’ were declared in NAMESPACE but not found ` 
How could I fix it?
Thanks in advance!

bw,
Zsolt

**Comment by hyunhwaj** [comment]
@gyzsolt91 

Can you run the tutorial without any problem? If you do, I would like you to install CB2 again with `install.package("CB2", dependencies=T)` command-line.

If you have the problem persistently, you may need to share your code or data to reproduce the error. And please provide outputs when you run `sessionInfo()` and `installed.packages()`

Thank you,

Hwan
