### ISSUE TITLE
run_sgrna_quant fails

### ISSUE THREAD

**Issue by AMChalkie** [LiuzLab/CB2#3]
Hi,

I see the following error:

Error in data.frame(sgRNA = quant_ret$sgRNA, sequence = quant_ret$sequence) : 
  arguments imply differing number of rows: 79633, 79637
> traceback()
3: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
2: data.frame(sgRNA = quant_ret$sgRNA, sequence = quant_ret$sequence)
1: run_sgrna_quant(LIBRARY_FASTA, df_design)

Suggest adding a more robust check in the output section.
Cheers
Alistair

**Comment by AMChalkie** [comment]
When running 
run_sgrna_quant(FASTA, df_design, sg2gene)
I see this comment: 4 sgRNA sequences were repetitive and will be discarded.

Final Mappability: 88.2023%
Parsed with column specification:
cols(
  PZP_1 = col_character(),
  PZP = col_character()
)
Error: `by` can't contain join column `id` which is missing from LHS
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
`by` can't contain join column `id` which is missing from LHS
Backtrace:
 1. CB2::run_sgrna_quant(...)
 3. dplyr:::left_join.tbl_df(df_map, df_count, by = "id")
 5. dplyr:::common_by.character(by, x, y)
 6. dplyr:::common_by.list(by, x, y)
 7. dplyr:::bad_args(...)
 8. dplyr:::glubort(fmt_args(args), ..., .envir = .envir)
Run `rlang::last_trace()` to see the full **context.**

When running: (with duplicates)
run_sgrna_quant(FASTA, df_design) 

run_sgrna_quant(FASTA, df_design)

I get 
Error in data.frame(sgRNA = quant_ret$sgRNA, sequence = quant_ret$sequence) :
arguments imply differing number of rows: 79633, 79637

traceback()
3: stop(gettextf("arguments imply differing number of rows: %s",
paste(unique(nrows), collapse = ", ")), domain = NA)
2: data.frame(sgRNA = quant_ret$sgRNA, sequence = quant_ret$sequence)
1: run_sgrna_quant(LIBRARY_FASTA, df_design)

**Comment by hyunhwaj** [comment]
Hi, can you share your fasta file?

Thank you,

Hyun-Hwan Jeong

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AMChalkie** [comment]
Here you go: 
[broadgpp_brie_crispr_library.fasta.gz](https://github.com/LiuzLab/CB2/files/3895077/broadgpp_brie_crispr_library.fasta.gz)
