### ISSUE TITLE
inconsistent between .fq.gz and .fastq?

### ISSUE THREAD

**Issue by AMChalkie** [LiuzLab/CB2#4]
Strange as this may sound, I get different results when using a .fq.gz vs a .fastq file (when the .fastq is a zcat of original). I get different mappability results (0.018 ish vs the expected 85%).

Would be great if this was handled automatically and input from .fq.gz was handled correctly, or alternatively at least a warning that this might be what's happening.

Otherwise - very useful software thank you!

**Comment by hyunhwaj** [comment]
Dear @AMChalkie,

The current version does not support gzipped FASTQ file, so you need to unzip the files. But the suggestion will be great for the CB^2. I will start to add the function soon.

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
@AMChalkie, the current github version supports gzipped FASTQ files. I wonder you are willing to test the version and let me know if you have any problem with that.

Thank you!

Hyun-Hwan Jeong

**Comment by AMChalkie** [comment]
Yes that works fine now. I notice that mappability information is not printed during the process now, which I thought was a good feature previously.

**Comment by hyunhwaj** [comment]
@AMChalkie you should see the message if you set the `verbose` parameter as `TRUE`.

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment]
@AMChalkie, Can you test on it again? The version which you tested has an incompatibility issue with Windows OS. So, I made some changes and wonder the change doesn't cause any problem.

Thank you,

Hyun-Hwan Jeong

**Comment by monovich** [comment]
Was just experimenting with **.fq.gz** vs **.fastq** inputs and it looks like **.fastq.gz** is not accepted for some reason. I think it would make sense to add support for it as **.fq.gz** and **.fastq.gz** are both fairly common.

**Comment by hyunhwan-jeong** [comment]
Not a problem, and as you figured out, it has to support both - https://github.com/LiuzLab/CB2/blob/57d7fd5548c162b175a9dc6f5a57f1f73822eb0d/R/helpers.R#L69
